---
title: "Hw5"
author: 'IRENE MARTINEZ MORATA (UNI: im2557)'
date: "11/19/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/irene/Desktop/DATA SCIENCE/p8105_mtp_im2557")

library(tidyverse)
library(readxl)
library(readr)
library(ggplot2)
library(lubridate)
library(ggridges)
library(ggpubr)
library(purrr)

getwd()
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",

  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 2

```{r }
df_homicides =
  read_csv("homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolution = case_when (
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>% 
  filter(city_state != "TulsaAL") %>% 
  relocate(city_state) 
```
